// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// DFtoMX
NumericMatrix DFtoMX(DataFrame df);
RcppExport SEXP _networkDepth_DFtoMX(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(DFtoMX(df));
    return rcpp_result_gen;
END_RCPP
}
// PTDSpaceC
Rcpp::NumericVector PTDSpaceC(Rcpp::NumericMatrix data);
RcppExport SEXP _networkDepth_PTDSpaceC(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(PTDSpaceC(data));
    return rcpp_result_gen;
END_RCPP
}
// PTDepthC
double PTDepthC(arma::rowvec x, arma::mat X);
RcppExport SEXP _networkDepth_PTDepthC(SEXP xSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(PTDepthC(x, X));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _networkDepth_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _networkDepth_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _networkDepth_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _networkDepth_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_networkDepth_DFtoMX", (DL_FUNC) &_networkDepth_DFtoMX, 1},
    {"_networkDepth_PTDSpaceC", (DL_FUNC) &_networkDepth_PTDSpaceC, 1},
    {"_networkDepth_PTDepthC", (DL_FUNC) &_networkDepth_PTDepthC, 2},
    {"_networkDepth_rcpparma_hello_world", (DL_FUNC) &_networkDepth_rcpparma_hello_world, 0},
    {"_networkDepth_rcpparma_outerproduct", (DL_FUNC) &_networkDepth_rcpparma_outerproduct, 1},
    {"_networkDepth_rcpparma_innerproduct", (DL_FUNC) &_networkDepth_rcpparma_innerproduct, 1},
    {"_networkDepth_rcpparma_bothproducts", (DL_FUNC) &_networkDepth_rcpparma_bothproducts, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_networkDepth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
