# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DFtoMX <- function(df) {
    .Call(`_networkDepth_DFtoMX`, df)
}

PTDSpaceC <- function(data) {
    .Call(`_networkDepth_PTDSpaceC`, data)
}

PTDepthC <- function(x, X) {
    .Call(`_networkDepth_PTDepthC`, x, X)
}

rcpparma_hello_world <- function() {
    .Call(`_networkDepth_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_networkDepth_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_networkDepth_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_networkDepth_rcpparma_bothproducts`, x)
}

